namespace PerceptronSimulator;

using System.Text;

/// <summary>
/// Exports perceptron circuit to KiCad schematic format (.kicad_sch)
/// for professional EDA editing and SPICE simulation.
/// </summary>
public class KiCadExporter
{
    private readonly int[] _inputs;
    private readonly double[] _weights;
    private readonly double _bias;
    private readonly bool[] _switchStates;
    private readonly int _nodeCount;

    public KiCadExporter(int[] inputs, double[] weights, double bias, bool[] switchStates, int nodeCount)
    {
        _inputs = inputs;
        _weights = weights;
        _bias = bias;
        _switchStates = switchStates;
        _nodeCount = nodeCount;
    }

    public string GenerateSchematic()
    {
        var sb = new StringBuilder();

        // KiCad schematic header
        sb.AppendLine("(kicad_sch (version 20230121) (generator perceptron_simulator)");
        sb.AppendLine();
        sb.AppendLine("  (uuid " + Guid.NewGuid().ToString() + ")");
        sb.AppendLine();
        sb.AppendLine("  (paper \"A4\")");
        sb.AppendLine();

        // Title block
        sb.AppendLine("  (title_block");
        sb.AppendLine("    (title \"Mark I Perceptron - Analog Summing Circuit\")");
        sb.AppendLine($"    (date \"{DateTime.Now:yyyy-MM-dd}\")");
        sb.AppendLine($"    (comment 1 \"Inputs: {_nodeCount}\")");
        sb.AppendLine($"    (comment 2 \"Feedback Rf: {PartsDatabase.FormatResistorValue(PartsDatabase.ReferenceResistor)}\")");
        sb.AppendLine("    (comment 3 \"Generated by Mark I Perceptron Simulator\")");
        sb.AppendLine("  )");
        sb.AppendLine();

        // Library symbols section
        sb.AppendLine("  (lib_symbols");
        AddLibrarySymbols(sb);
        sb.AppendLine("  )");
        sb.AppendLine();

        // Components and wiring
        int yPos = 100;
        int xInput = 50;
        int xOpAmp = 150;

        // Power supply
        AddPowerSupply(sb, 20, 20);

        // Input channels
        for (int i = 0; i < _nodeCount; i++)
        {
            int y = yPos + i * 15;
            bool isOn = i < _switchStates.Length && _switchStates[i];
            double weight = i < _weights.Length ? _weights[i] : 0;
            double resistorValue = PartsDatabase.CalculateInputResistance(weight);

            AddInputChannel(sb, i + 1, xInput, y, isOn, resistorValue, weight);
        }

        // Op-amp (LM358)
        AddOpAmp(sb, xOpAmp, yPos + (_nodeCount * 15) / 2);

        // Feedback resistor
        AddFeedbackResistor(sb, xOpAmp - 20, yPos + (_nodeCount * 15) / 2 - 20);

        // Output LED circuit
        AddOutputLED(sb, xOpAmp + 50, yPos + (_nodeCount * 15) / 2);

        // Power symbols
        AddPowerSymbols(sb);

        // Nets (wiring connections) - CRITICAL for circuit to work
        sb.AppendLine();
        sb.AppendLine("  ; === NETLIST: Electrical Connections ===");
        sb.AppendLine();

        AddNets(sb, xInput, yPos, xOpAmp);

        sb.AppendLine(")");

        return sb.ToString();
    }

    private void AddPowerSymbols(StringBuilder sb)
    {
        // +5V power symbol
        sb.AppendLine("  (symbol (lib_id \"power:+5V\") (at 100 20 0)");
        sb.AppendLine("    (property \"Reference\" \"#PWR01\" (at 100 15 0))");
        sb.AppendLine("    (property \"Value\" \"+5V\" (at 100 24 0))");
        sb.AppendLine("    (uuid " + Guid.NewGuid().ToString() + ")");
        sb.AppendLine("  )");

        // GND power symbol
        sb.AppendLine("  (symbol (lib_id \"power:GND\") (at 100 200 0)");
        sb.AppendLine("    (property \"Reference\" \"#PWR02\" (at 100 205 0))");
        sb.AppendLine("    (property \"Value\" \"GND\" (at 100 196 0))");
        sb.AppendLine("    (uuid " + Guid.NewGuid().ToString() + ")");
        sb.AppendLine("  )");
    }

    private void AddNets(StringBuilder sb, int xInput, int yStart, int xOpAmp)
    {
        // +5V power rail
        sb.AppendLine($"  (wire (pts (xy 20 20) (xy 100 20)))  ; +5V distribution");
        sb.AppendLine($"  (wire (pts (xy 100 20) (xy {xOpAmp} 20)))  ; +5V to op-amp");

        // Net 2: GND power rail
        sb.AppendLine($"  (wire (pts (xy 20 200) (xy 100 200)))  ; GND distribution");
        sb.AppendLine($"  (wire (pts (xy 100 200) (xy {xOpAmp} 200)))  ; GND to op-amp");

        // Nets 3+: Input channels (switch → resistor → summing junction)
        for (int i = 0; i < _nodeCount; i++)
        {
            int y = yStart + i * 15;
            sb.AppendLine($"  ; Input {i + 1}");
            sb.AppendLine($"  (wire (pts (xy {xInput} {y}) (xy {xInput + 20} {y})))  ; SW{i + 1} to R{i + 1}");
            sb.AppendLine($"  (wire (pts (xy {xInput + 40} {y}) (xy {xOpAmp - 20} {y})))  ; R{i + 1} to summing junction");
        }

        // Net: Summing junction to op-amp Pin 2 (IN-)
        int sumY = yStart + (_nodeCount * 15) / 2;
        sb.AppendLine($"  (wire (pts (xy {xOpAmp - 20} {sumY}) (xy {xOpAmp} {sumY - 8})))  ; Sum junction to op-amp IN-");

        // Net: Feedback resistor (Pin 1 to Pin 2)
        sb.AppendLine($"  (wire (pts (xy {xOpAmp + 50} {sumY}) (xy {xOpAmp - 20} {sumY - 20})))  ; Op-amp OUT to Rf");
        sb.AppendLine($"  (wire (pts (xy {xOpAmp - 20} {sumY - 20}) (xy {xOpAmp} {sumY - 8})))  ; Rf to op-amp IN-");

        // Net: Op-amp Pin 3 to GND
        sb.AppendLine($"  (wire (pts (xy {xOpAmp} {sumY + 8}) (xy {xOpAmp} 200)))  ; Op-amp IN+ to GND");

        // Net: Op-amp output to LED
        sb.AppendLine($"  (wire (pts (xy {xOpAmp + 50} {sumY}) (xy {xOpAmp + 70} {sumY})))  ; Op-amp OUT to LED resistor");
        sb.AppendLine($"  (wire (pts (xy {xOpAmp + 70} {sumY}) (xy {xOpAmp + 90} {sumY})))  ; LED resistor to LED");
        sb.AppendLine($"  (wire (pts (xy {xOpAmp + 90} {sumY}) (xy {xOpAmp + 90} 200)))  ; LED to GND");
    }

    private void AddLibrarySymbols(StringBuilder sb)
    {
        // Simplified library symbols - KiCad will resolve from standard libraries
        sb.AppendLine("    (symbol \"Device:R\" (pin_numbers hide) (pin_names (offset 0)))");
        sb.AppendLine("    (symbol \"Device:LED\" (pin_numbers hide))");
        sb.AppendLine("    (symbol \"Amplifier_Operational:LM358\" (pin_names (offset 0.127)))");
        sb.AppendLine("    (symbol \"Switch:SW_SPDT\" (pin_numbers hide))");
        sb.AppendLine("    (symbol \"Regulator_Linear:LM7805_TO220\" (pin_names (offset 0.254)))");
        sb.AppendLine("    (symbol \"Device:C\" (pin_numbers hide))");
        sb.AppendLine("    (symbol \"Device:Battery\" (pin_numbers hide))");
        sb.AppendLine("    (symbol \"power:+5V\" (power))");
        sb.AppendLine("    (symbol \"power:GND\" (power))");
    }

    private void AddPowerSupply(StringBuilder sb, int x, int y)
    {
        // 9V Battery
        sb.AppendLine($"  (symbol (lib_id \"Device:Battery\") (at {x} {y} 0)");
        sb.AppendLine($"    (property \"Reference\" \"BAT1\" (at {x} {y - 5} 0))");
        sb.AppendLine($"    (property \"Value\" \"9V\" (at {x} {y + 5} 0))");
        sb.AppendLine("    (uuid " + Guid.NewGuid().ToString() + ")");
        sb.AppendLine("  )");

        // LM7805 Voltage Regulator
        sb.AppendLine($"  (symbol (lib_id \"Regulator_Linear:LM7805_TO220\") (at {x + 30} {y} 0)");
        sb.AppendLine($"    (property \"Reference\" \"U2\" (at {x + 30} {y - 5} 0))");
        sb.AppendLine($"    (property \"Value\" \"LM7805\" (at {x + 30} {y + 5} 0))");
        sb.AppendLine("    (uuid " + Guid.NewGuid().ToString() + ")");
        sb.AppendLine("  )");

        // Filter capacitors
        sb.AppendLine($"  (symbol (lib_id \"Device:C\") (at {x + 50} {y} 0)");
        sb.AppendLine($"    (property \"Reference\" \"C1\" (at {x + 50} {y - 5} 0))");
        sb.AppendLine($"    (property \"Value\" \"10uF\" (at {x + 50} {y + 5} 0))");
        sb.AppendLine("    (uuid " + Guid.NewGuid().ToString() + ")");
        sb.AppendLine("  )");

        sb.AppendLine($"  (symbol (lib_id \"Device:C\") (at {x + 60} {y} 0)");
        sb.AppendLine($"    (property \"Reference\" \"C2\" (at {x + 60} {y - 5} 0))");
        sb.AppendLine($"    (property \"Value\" \"0.1uF\" (at {x + 60} {y + 5} 0))");
        sb.AppendLine("    (uuid " + Guid.NewGuid().ToString() + ")");
        sb.AppendLine("  )");
    }

    private void AddInputChannel(StringBuilder sb, int num, int x, int y, bool isOn, double resistorValue, double weight)
    {
        string refR = $"R{num}";
        string refSW = $"SW{num}";
        string refLED = $"D{num}";

        // SPDT Switch
        sb.AppendLine($"  (symbol (lib_id \"Switch:SW_SPDT\") (at {x} {y} 0)");
        sb.AppendLine($"    (property \"Reference\" \"{refSW}\" (at {x} {y - 5} 0))");
        sb.AppendLine($"    (property \"Value\" \"SPDT\" (at {x} {y + 5} 0))");
        bool swapWiring = weight > 0.01;
        sb.AppendLine($"    (property \"Comment\" \"{'('}Swap wiring for positive weight{')'}\" (at {x} {y + 8} 0))");
        sb.AppendLine("    (uuid " + Guid.NewGuid().ToString() + ")");
        sb.AppendLine("  )");

        // Input LED
        sb.AppendLine($"  (symbol (lib_id \"Device:LED\") (at {x + 20} {y} 0)");
        sb.AppendLine($"    (property \"Reference\" \"{refLED}\" (at {x + 20} {y - 5} 0))");
        sb.AppendLine($"    (property \"Value\" \"Green\" (at {x + 20} {y + 5} 0))");
        sb.AppendLine("    (uuid " + Guid.NewGuid().ToString() + ")");
        sb.AppendLine("  )");

        // Input resistor
        string rValue = FormatResistanceForKiCad(resistorValue);
        sb.AppendLine($"  (symbol (lib_id \"Device:R\") (at {x + 40} {y} 0)");
        sb.AppendLine($"    (property \"Reference\" \"{refR}\" (at {x + 40} {y - 5} 0))");
        sb.AppendLine($"    (property \"Value\" \"{rValue}\" (at {x + 40} {y + 5} 0))");
        sb.AppendLine($"    (property \"Comment\" \"Weight: {weight:+0.00;-0.00}\" (at {x + 40} {y + 8} 0))");
        sb.AppendLine("    (uuid " + Guid.NewGuid().ToString() + ")");
        sb.AppendLine("  )");
    }

    private void AddOpAmp(StringBuilder sb, int x, int y)
    {
        // LM358 Dual Op-Amp (using section A)
        sb.AppendLine($"  (symbol (lib_id \"Amplifier_Operational:LM358\") (at {x} {y} 0) (unit 1)");
        sb.AppendLine($"    (property \"Reference\" \"U1\" (at {x} {y - 10} 0))");
        sb.AppendLine($"    (property \"Value\" \"LM358\" (at {x} {y + 10} 0))");
        sb.AppendLine($"    (property \"Spice_Primitive\" \"X\" (at {x} {y + 15} 0))");
        sb.AppendLine($"    (property \"Spice_Model\" \"LM358\" (at {x} {y + 18} 0))");
        sb.AppendLine("    (uuid " + Guid.NewGuid().ToString() + ")");
        sb.AppendLine("  )");
    }

    private void AddFeedbackResistor(StringBuilder sb, int x, int y)
    {
        string rfValue = PartsDatabase.FormatResistorValue(PartsDatabase.ReferenceResistor);
        sb.AppendLine($"  (symbol (lib_id \"Device:R\") (at {x} {y} 0)");
        sb.AppendLine($"    (property \"Reference\" \"Rf\" (at {x} {y - 5} 0))");
        sb.AppendLine($"    (property \"Value\" \"{rfValue}\" (at {x} {y + 5} 0))");
        sb.AppendLine($"    (property \"Comment\" \"Feedback resistor\" (at {x} {y + 8} 0))");
        sb.AppendLine("    (uuid " + Guid.NewGuid().ToString() + ")");
        sb.AppendLine("  )");
    }

    private void AddOutputLED(StringBuilder sb, int x, int y)
    {
        // Current limiting resistor
        string rValue = PartsDatabase.FormatResistorValue(PartsDatabase.Resistor470R.Resistance ?? 470);
        sb.AppendLine($"  (symbol (lib_id \"Device:R\") (at {x} {y} 0)");
        sb.AppendLine($"    (property \"Reference\" \"R_LED\" (at {x} {y - 5} 0))");
        sb.AppendLine($"    (property \"Value\" \"{rValue}\" (at {x} {y + 5} 0))");
        sb.AppendLine("    (uuid " + Guid.NewGuid().ToString() + ")");
        sb.AppendLine("  )");

        // Output LED
        sb.AppendLine($"  (symbol (lib_id \"Device:LED\") (at {x + 20} {y} 0)");
        sb.AppendLine($"    (property \"Reference\" \"D_OUT\" (at {x + 20} {y - 5} 0))");
        sb.AppendLine($"    (property \"Value\" \"Green\" (at {x + 20} {y + 5} 0))");
        sb.AppendLine("    (uuid " + Guid.NewGuid().ToString() + ")");
        sb.AppendLine("  )");
    }

    private string FormatResistanceForKiCad(double ohms)
    {
        if (ohms >= 1000000)
            return $"{ohms / 1000000:0.##}M";
        else if (ohms >= 1000)
            return $"{ohms / 1000:0.##}k";
        else
            return $"{ohms:0}";
    }

    /// <summary>
    /// Export schematic to KiCad format and save to file.
    /// </summary>
    public void ExportToFile(string filePath)
    {
        string schematic = GenerateSchematic();
        File.WriteAllText(filePath, schematic);
    }
}
