//
//  PerceptronSnapshot.swift
//  PerceptronDemo
//
//  The serializable panel state written to / read from `.pcn` files — used by
//  the gear-menu Save/Load, by bundled preset examples, and by the XCTest that
//  generates those presets. Kept out of the view controller so both the app and
//  the tests can share one definition.
//

import Foundation

/// The full panel state persisted in a `.pcn` file. Mirrors the desktop app's
/// `PerceptronData`, plus the live switch pattern so a saved file restores
/// exactly what was on screen.
struct PerceptronSnapshot: Codable, Equatable {
    var gridSize: Int
    var weights: [Double]
    var bias: Double
    var learningRate: Double
    var switchStates: [Bool]

    /// The file extension used for saved snapshots (JSON payload).
    static let fileExtension = "pcn"

    /// Pretty-printed, key-sorted JSON — stable output so regenerated preset
    /// files diff cleanly in git.
    func jsonData() throws -> Data {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        return try encoder.encode(self)
    }

    static func decode(from data: Data) throws -> PerceptronSnapshot {
        try JSONDecoder().decode(PerceptronSnapshot.self, from: data)
    }
}

/// The catalog of pre-trained example networks bundled with the app. Each case
/// is backed by a `<rawValue>.pcn` file in the app bundle, generated by
/// `PresetGeneratorTests` (running the tests regenerates them from scratch, so
/// the bundled files are always provably trained).
enum Preset: String, CaseIterable {
    case topVsBottom   = "TopVsBottom"
    case leftVsRight   = "LeftVsRight"
    case diagonal      = "Diagonal"
    case density       = "Density"

    /// The label shown in the gear menu's "Load Example" submenu.
    var menuTitle: String {
        switch self {
        case .topVsBottom: return "Top vs Bottom"
        case .leftVsRight: return "Left vs Right"
        case .diagonal:    return "Diagonal"
        case .density:     return "Mostly On vs Mostly Off"
        }
    }

    /// SF Symbol shown alongside the menu item.
    var symbolName: String {
        switch self {
        case .topVsBottom: return "arrow.up.and.down.square"
        case .leftVsRight: return "arrow.left.and.right.square"
        case .diagonal:    return "line.diagonal"
        case .density:     return "circle.grid.3x3.fill"
        }
    }

    /// Loads and decodes the bundled `.pcn` for this preset, or nil if it's
    /// missing / unreadable (e.g. the generator test hasn't been run).
    func loadSnapshot(from bundle: Bundle = .main) -> PerceptronSnapshot? {
        guard let url = bundle.url(forResource: rawValue, withExtension: PerceptronSnapshot.fileExtension),
              let data = try? Data(contentsOf: url) else {
            return nil
        }
        return try? PerceptronSnapshot.decode(from: data)
    }
}
